config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#about'
  get :about,         to: 'static_pages#about'
  get :use_of_terms,  to: 'static_pages#terms'

  devise_for :users, controllers: {
            omniauth_callbacks: "users/omniauth_callbacks",
            registrations: "users/registrations",
            passwords: "users/passwords"
          }
           
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#new_guest"
    delete "/users/sign_out", to: "devise/sessions#destroy"
  end

  resources :users, only: [:show, :create, :edit, :update, :destroy] do
    member do 
      get :following, :followers
    end
  end


  resources :relationships, only: [:create, :destroy]
  resources :posts do
    resources :likes, only: [:create]
    resource :like, only: [:destroy]
    resources :metoos, only: [:create]
    resource :metoo, only: [:destroy]
    resources :comments, only: [:create]
  resources :comments, only: [:edit, :update, :destroy]
  end
end

app/models/metoo.rb
class Metoo < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates_uniqueness_of :post_id, scope: :user_id
end

app/controllers/metoos_controller.rb
class MetoosController < ApplicationController
    before_action :set_post
    # before_aciton :authenticate_user!

  def create
    if @post.user_id != current_user.id
      @metoo = Metoo.create(user_id: current_user.id, post_id: @post.id)
    end
  end

  def destroy
    @metoo = Metoo.find_by(user_id: current_user.id, post_id: @post.id).destroy
  end

  private

  def set_post
    @post = Post.find(params[:post_id])
  end
end

app/helpers/metoos_helper.rb
module MetoosHelper
end

app/views/metoos/_metoo.html.erb
  <% if current_user.metooed_by?(post.id) %>
    <%= link_to post_metoo_path(post.id), class: "metoo-format", method: :delete, remote: true do %>
      <div class="fas fa-hand-paper"></div>
    <% end %>
      <span>行ったよ</span>
      <%= post.metoos.count %>
  <% else %>
    <%= link_to post_metoos_path(post.id), class: "metoo-format", method: :post, remote: true do %>
      <div class="far fa-hand-paper"></div>
    <% end %>
      <span>行ったよ</span>
    <%= post.metoos.count %>
  <% end %>

app/views/metoos/create.js.erb
$("#metoo_<%= @post.id %>").html('<%= j(render partial: "metoos/metoo", locals: { post: @post }) %>');

app/views/metoos/destroy.js.erb
$("#metoo_<%= @post.id %>").html('<%= j(render partial: "metoos/metoo", locals: { post: @post }) %>');