config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#about'
  get :about,         to: 'static_pages#about'
  get :use_of_terms,  to: 'static_pages#terms'

  devise_for :users, controllers: {
            omniauth_callbacks: "users/omniauth_callbacks",
            registrations: "users/registrations",
            passwords: "users/passwords"
          }
           
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#new_guest"
    delete "/users/sign_out", to: "devise/sessions#destroy"
  end

  resources :users, only: [:show, :create, :edit, :update, :destroy] do
    member do 
      get :following, :followers
    end
  end


  resources :relationships, only: [:create, :destroy]
  resources :posts do
    resources :likes, only: [:create]
    resource :like, only: [:destroy]
    resources :metoos, only: [:create]
    resource :metoo, only: [:destroy]
    resources :comments, only: [:create]
  resources :comments, only: [:edit, :update, :destroy]
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable,
         :omniauthable

  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :metoos, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_one_attached :avatar

  has_many :following_relationships, foreign_key: "follower_id", class_name: "Relationship", dependent: :destroy
  has_many :following, through: :following_relationships
  has_many :follower_relationships, foreign_key: "following_id", class_name: "Relationship", dependent: :destroy
  has_many :followers, through: :follower_relationships

  #フォローしているかを確認するメソッド
  def following?(user)
    following_relationships.find_by(following_id: user.id)
  end

  #フォローするときのメソッド
  def follow(user)
    following_relationships.create!(following_id: user.id)
  end

  #フォローを外すときのメソッド
  def unfollow(user)
    following_relationships.find_by(following_id: user.id).destroy
  end

  def liked_by?(post_id)
    likes.where(post_id: post_id).exists?
  end

  def metooed_by?(post_id)
    metoos.where(post_id: post_id).exists?
  end

  def self.find_for_oauth(auth)
    user = User.where(uid: auth.uid, provider: auth.provider).first

    unless user
      user = User.new(
        uid: auth.uid,
        provider: auth.provider,
        email: auth.info.email,
        password: Devise.friendly_token[0,20],
        name: auth.info.name
      )
      user.skip_confirmation!
      user.save(validate: false) 
    end
    user
  end

  def feed
    following_ids = "SELECT followed_id FROM relationships
                     WHERE follower_id = :user_id"
    Post.where("user_id IN (#{following_ids})
                     OR user_id = :user_id", user_id: id)
  end

  def update_without_current_password(params, *options)
    params.delete(:current_password)

    if params[:password].blank? && params[:password_confirmation].blank?
      params.delete(:password)
      params.delete(:password_confirmation)
    end
    result = update_attributes(params, *options)
    clean_up_passwords
    result
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    callback_from :facebook
  end

  def google_oauth2
    callback_from :google
  end

  
  private
  def callback_from(provider)
    provider = provider.to_s
    @user = User.find_for_oauth(request.env['omniauth.auth'])
    @user.skip_confirmation! 

    if @user.persisted?
      flash[:notice] = I18n.t('devise.omniauth_callbacks.success', kind: provider.capitalize)
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.#{provider}_data"] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  before_action :check_guest, only: :create
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :check_guest, only: %i[update destroy]
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_update_params, only: [:update]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  def configure_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:introduction, :sex])
    
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

  def update_resource(resource, params)
    resource.update_without_current_password(params)
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  def new_guest
    user = User.find_or_create_by!(email: 'guest@example.com', name: 'ゲストユーザー') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.confirmed_at = Time.now  # Confirmable を使用している場合は必要
    end
    sign_in user
    redirect_to posts_path, notice: 'ゲストログインしました。'
  end

  # GET /resource/sign_in
  def new
    session.delete('devise.omniauth_data')
    super
  end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:show]

  def index
    # @users = User.page
  end
 
  # def edit
  #   @user = User.find(params[:id])
  # end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.page(params[:page]).per(5)

    metoos = Metoo.where(user_id: current_user.id).pluck(:post_id)  # ログイン中のユーザーの行ったよのpost_idカラムを取得
    @metoo_list = Post.find(metoos)     # postsテーブルから、お気に入り登録済みのレコードを取得
  end

  def following
      #@userがフォローしているユーザー
      @user  = User.find(params[:id])
      @users = @user.following.page(params[:page]).per(5)
      render 'show_follow'
  end

  def follower
      #@userをフォローしているユーザー
      @user  = User.find(params[:id])
      @users = @user.followers.page(params[:page]).per(5)
      render 'show_follow'
  end

  private

  # ユーザー新規作成時に許可する属性
  def user_params
    params.require(:user).permit(:name, :email, :password,
                                  :password_confirmation)
  end

    # プロフィール編集時に許可する属性
  def user_params_update
    params.require(:user).permit(:name, :email, :introduction, :familiar_place)
  end

    # 正しいユーザーかどうか確認
  def correct_user
    @user = User.find(params[:id])
    if current_user != @user
      flash[:danger] = "このページへはアクセスできません"
      redirect_to(root_url)
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, size: 80)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end

  def current_user?(user)
    user == current_user
  end
  
end

app/views/users/_follow.html.erb
<%= form_for(current_user, url: relationships_path, method: :post, remote: true) do |f| %>
  <%= hidden_field_tag :following_id, @user.id %>
  <%= f.submit "フォローする", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<!-- フォローボタン: プロフィールのユーザーがcurrent_userでなければ表示--->
<% unless current_user?(@user) %>
  <div id="follow_form">
    <% if current_user.following?(@user) %>
      <%= render "unfollow" %>
    <% else %>
      <%= render "follow" %>
    <% end %>
  </div>
<% end %>

app/views/users/_followers.html.erb
<h1>Users#followers</h1>
<% @users.each do |user|

    <% if current_user != user %>
        <% if user.followed_by?(current_user) %>
            <p><%=link_to "フォロー済み", user_relationships_path(user.id), method: :delete %></p>
        <% else %>
            <p><%=link_to "フォローする", user_relationships_path(user.id), method: :post %></p>
        <% end %>
    <% end %>
<% end

app/views/users/_follows.html.erb
<h1>Users#follows</h1>
<p>Find me in app/views/users/follows.html.erb</p>

<% @users.each do |user| %>
  <hr>

    <% if current_user != user %>
        <% if user.followed_by?(current_user) %>
            <p><%=link_to "フォロー済み", user_relationships_path(user.id), method: :delete %></p>
        <% else %>
            <p><%=link_to "フォローする", user_relationships_path(user.id), method: :post %></p>
        <% end %>
    <% end %>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user, url: relationship_path(@user), method: :delete, remote: true) do |f| %>
  <%= f.submit "フォロー解除", class: "btn btn-danger" %>
<% end %>

app/views/users/followers.html.erb
<h1>Users#followers</h1>
<% @users.each do |user|

    <% if current_user != user %>
        <% if user.followed_by?(current_user) %>
            <p><%=link_to "フォロー済み", user_relationships_path(user.id), method: :delete %></p>
        <% else %>
            <p><%=link_to "フォローする", user_relationships_path(user.id), method: :post %></p>
        <% end %>
    <% end %>
<% end

app/views/users/follows.html.erb
<h1>Users#follows</h1>
<p>Find me in app/views/users/follows.html.erb</p>

<% @users.each do |user| %>
  <hr>

    <% if current_user != user %>
        <% if user.followed_by?(current_user) %>
            <p><%=link_to "フォロー済み", user_relationships_path(user.id), method: :delete %></p>
        <% else %>
            <p><%=link_to "フォローする", user_relationships_path(user.id), method: :post %></p>
        <% end %>
    <% end %>
<% end %>

app/views/users/show.html.erb
<div class="container">
  <% provide(:title, "マイページ") %>
    <h1>マイページ</h1>
      <% if @user.avatar.attached? %>
        <p><%= image_tag @user.avatar.variant(combine_options:{gravity: :center, resize:"200x200^", crop:"200x200+0+0"}).processed %></p>
      <% end %>
      <div class="col-md-8">
        <h4 class="show-user-name">
          <%= @user.name %><br>
        </h4>
        <div class="show-user-introduction">
          <%= @user.introduction %>
        </div>
          <p>登録日 : <%= @user.created_at.to_s(:datetime_jp) %></p>
          <p>更新日 : <%= @user.updated_at.to_s(:datetime_jp) %></p>
          <section class="stats">
            <%= render 'devise/shared/stats' %>
          </section><br>
          <% if current_user.id == @user.id %>
            <a class="nav-link" href="/users/edit">プロフィール編集</a>
          <% end %>
            <%= render 'follow_form' if user_signed_in? %>
      </div>
        <div class="row">
          <div class="col-md-9">
            <% if @user.posts.any? %>
              <h3>投稿数 <%= @user.posts.count %>件</h3>

            <!--プロフィールに表示しているユーザーの投稿一覧を見せる -->
              <% @metoo_list.each do |post| %>
                <p>行った日 : <%= post.date.strftime("%Y年%m月%d日") %></p>
                <p>タイトル ： <%= post.title %></p>
                <p>内容 ： <%= post.content %></p><hr>
              <% end %>
 
            <% end %>
          </div>
        </div>
      </div>

app/views/users/show_follow.html.erb
<div class="container">
<% provide(:title, @title) %>
<div id="fh5co-portfolio">
  <div class="container">
    <div class="row">
      <aside class="col-md-4">
        <section class="user_info">
        <% if @user.avatar.attached? %>
            <p><%= image_tag @user.avatar.variant(combine_options:{gravity: :center, resize:"200x200^", crop:"200x200+0+0"}).processed %></p>
        <% end %>
          <h2><%= @user.name %></h2>
          <span><%= link_to "プロフィール", @user %></span>
          <span><b>投稿</b><%= @user.posts.count %><b>件</b></span>
        </section>
        <section class="stats">
          <%= render 'devise/shared/stats' %>
          <% if @users.any? %>
            <div class="user_avatars">
              <% @users.each do |user| %>
                <%= link_to gravatar_for(user, size: 30), user %>
              <% end %>
            </div>
          <% end %>
        </section>
      </aside>
      <div class="col-md-8">
        <h3><%#= @title %></h3>
        <% if @users.any? %>
          <ul class="users follow">
            <%#= render @users %>
          </ul>
          <%#= will_paginate %>
          <!-- 部分テンプレートにしなくてもいい、何したいかはっきりさせる-->
        <% end %>
      </div>
    </div>
  </div>
</div>
</div>