config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#about'
  get :about,         to: 'static_pages#about'
  get :use_of_terms,  to: 'static_pages#terms'

  devise_for :users, controllers: {
            omniauth_callbacks: "users/omniauth_callbacks",
            registrations: "users/registrations",
            passwords: "users/passwords"
          }
           
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#new_guest"
    delete "/users/sign_out", to: "devise/sessions#destroy"
  end

  resources :users, only: [:show, :create, :edit, :update, :destroy] do
    member do 
      get :following, :followers
    end
  end


  resources :relationships, only: [:create, :destroy]
  resources :posts do
    resources :likes, only: [:create]
    resource :like, only: [:destroy]
    resources :metoos, only: [:create]
    resource :metoo, only: [:destroy]
    resources :comments, only: [:create]
  resources :comments, only: [:edit, :update, :destroy]
  end
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :likes, dependent: :destroy
  has_many :metoos, dependent: :destroy
  has_many :comments, dependent: :destroy
  belongs_to :user
  has_many_attached :images

  validate :image_type
  validate :image_size
  validates :title, presence: true, length: {maximum: 140 }
  validates :content, length: { maximum: 3000 }
  validates :date, presence: true


  private

  #一つにしても良いので後ほどやるelseif
  def image_type
    if images.attached?
      images.each do |image|
        if !image.blob.content_type.in?(%('image/jpeg image/png image/jpg'))
          image.purge
          errors.add(:images, 'はjpegまたはpngまたはjpg形式でアップロードしてください')
       end
      end
    end
  end

  def image_size
    if images.attached?
    images.each do |image|
       if image.blob.byte_size > 5.megabytes
         image.purge
         errors.add(:images, "は1つのファイル5MB以内にしてください")
       end
    end
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/edit.html.erb
<%= form_with(model: @post, local: true) do |f| %>
  <div class="container">
  <div>
    <%= f.label :title, "タイトル" %><br>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :content, "投稿内容" %><br>
    <%= f.text_area :content %>
  </div>
  <%= f.submit %>
  </div>
<% end %>

app/views/posts/index.html.erb
  <div class="container">
  <h1>投稿一覧</h1>
    <div class="row">
       <% if user_signed_in? %>
        <div class="col-md-4">
          <%= search_form_for @search, url: posts_path do |f| %>
            <%= f.search_field :title_or_content_cont, placeholder: "タイトルか内容で検索", class: 'form-control' %>
          <% end %>
        </div>
        <% @results.each do |post| %>
          <div class="post">  
            <hr><div class="d-flex flex-row mt-3">
              <div class="picture">
                <% if post.images.attached? %>
                  <% post.images.each do |image| %>
                    <p><%= image_tag image.variant(resize_to_limit: [300, 300]) %></p>
                  <% end %>
                <% end %>
                <div id="post_<%= post.id %>">  
                  <%= render partial: 'likes/like', locals: { post: post } %>
                </div>
                <div id="metoo_<%= post.id %>">  
                  <%= render partial: 'metoos/metoo', locals: { post: post } %>
                </div>
              </div>

              <div class="mx-5">
                <p>行った日 : <%= post.date&.strftime("%Y年%m月%d日") %></p>
                <p>場所 : <%= post.place %></p>
                <p>タイトル : <%= post.title %></p>
                <p>内容 : <%= simple_format(post.content) %></p>
              </div>
           
             <div>
              <div class="post-user">
                <%= link_to post.user.name, user_path(post.user) %>
              </div>
              <div class="post-created-at">
                <%= time_ago_in_words(post.created_at) %>前に投稿
              </div>
             </div>
          </div>

              <%= link_to "詳細", post, class: "btn btn-link" %>
              <% if user_signed_in? && current_user.id == post.user_id %>
                <%= link_to "編集", edit_post_path(post.id), class: "btn btn-link" %>
                <%= link_to "削除", post, method: :delete, data: { confirm: '本当に削除していいですか?', cancel: 'やめる', commit: '削除する'}, title: '削除確認', class: "btn btn-link" %>
              <% end %>

        <% end %>
      </div>  
  </div>
     <% else %>
        <p>ログインしてください</p>
     <% end %>
    <%= paginate @results %>

app/views/posts/new.html.erb
  <div class="container">
  <h1>投稿を入力</h1>
  <%= form_with model: @post, local: true do |f| %>

  <div class="col-md-3">
    <p><%= f.label :date, "行った日" %> <span class="input-need">※必須</span><%= f.date_field :date, class: 'form-control' %></p>
  </div>
    
  <div class="col-md-6">
  <p><%= f.label :title, "タイトル" %> <span class="input-need">※必須</span> <%= f.text_field :title, class: 'form-control' %></p>

  <div class="form-group">
  <p><%= f.label :content, "内容" %> <span class="input-need">※必須</span> <%= f.text_area :content, class: 'form-control' %></p>
  <p><%= f.label :place, "フットサル場" %> <span class="input-need">※必須</span> <%= f.text_field :place, class: 'form-control' %></p>
  </div>

　<p><%= f.label :category, "カテゴリー" %><%= f.select :category, [["ウルトラビギナー", "ウルトラビギナー"], ["ビギナー", "ビギナー"], ["エンジョイ", "エンジョイ"], ["ガチ", "ガチ"]], include_blank: "選択して下さい" %></p>

  <p><%= f.label :shoes_color, "シューズの色" %> <span class="input-unneed">※任意</span> <%= f.text_field :shoes_color, class: 'form-control' %></p>
  <p><%= f.label :shirts_color, "シャツの色" %> <span class="input-unneed">※任意</span> <%= f.text_field :shirts_color, class: 'form-control' %></p>
 </div>

  <p><%= f.label :images, "画像" %> <span class="input-unneed">※任意</span> <%= f.file_field :images, multiple: true %></p>

  <%= f.submit "送信", class: "btn btn-primary" %>
<% end %>
</div>

app/views/posts/show.html.erb
<div class="container">
<h1>投稿詳細</h1>
<p><span>タイトル: </span><%= @post.title %></p>
<p><span>内容: </span><%= @post.content %></p>
<p><span>シューズの色: </span><%= @post.shoes_color %></p>
<p><span>シャツの色: </span><%= @post.shirts_color %></p>
<p><span>カテゴリー: </span><%= @post.category %></p>
<p><span>フットサル場: </span><%= @post.place %></p>

<% if @post.images.attached? %>
  <% @post.images.each do |image| %>
    <%= image_tag image.variant(resize_to_limit: [300, 300]) %>
  <% end %>
<% end %>

<% if @post.user_id == current_user.id %>
  <%= link_to("編集", "/posts/#{@post.id}/edit", class: "btn btn-primary") %>
  <%= link_to("削除", "/posts/#{@post.id}", class: "btn btn-primary", method: :delete, data: {confirm: "本当に削除しますか?"}) %>
<% end %> 
<div>
  <%= form_with(model: [@post, @comment], local: true) do |f| %>
    <div>
      <%= f.label :body, "コメント" %><br>
      <%= f.text_area :body %>
    </div>
    <%= f.submit "投稿", class: "btn btn-primary" %>
  <% end %>
  </div>
  <hr>
  <div>
    <% @post.comments.each do |comment| %>
      <p><%= comment.body %></p>
    <% end %>
  </div>
</div>