config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#about'
  get :about,         to: 'static_pages#about'
  get :use_of_terms,  to: 'static_pages#terms'

  devise_for :users, controllers: {
            omniauth_callbacks: "users/omniauth_callbacks",
            registrations: "users/registrations",
            passwords: "users/passwords"
          }
           
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#new_guest"
    delete "/users/sign_out", to: "devise/sessions#destroy"
  end

  resources :users, only: [:show, :create, :edit, :update, :destroy] do
    member do 
      get :following, :followers
    end
  end


  resources :relationships, only: [:create, :destroy]
  resources :posts do
    resources :likes, only: [:create]
    resource :like, only: [:destroy]
    resources :metoos, only: [:create]
    resource :metoo, only: [:destroy]
    resources :comments, only: [:create]
  resources :comments, only: [:edit, :update, :destroy]
  end
end

app/views/layouts/_breadcrumbs.html.haml
.breadcrumbs
  = breadcrumbs separator: " &rsaquo; ", class: "breadcrumbs-list"

app/views/layouts/_flash.html.erb
     <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>

app/views/layouts/_footer.html.erb
<hr><footer id="fh5co-footer" role="contentinfo"　.border-top>
    <div class="row copyright">
      <div class="col-md-12 text-center">
        <p>
          <small class="block">&copy; 2020 Co-sal Board All Rights Reserved.</small>
        </p>
      </div>
    </div>
</footer>

app/views/layouts/_header.html.erb
<header> 
   <nav class="navbar navbar-expand-lg navbar-dark" style="background-color:#3498db;">
     <a class="navbar-brand h5" href="/about">Co-sal Board</a>
     <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
       <span class="navbar-toggler-icon"></span>
     </button>
       <div class="collapse navbar-collapse" id="navbarSupportedContent">
         <ul class="navbar-nav mr-auto">
           <% if user_signed_in? %>
             <li class="nav-item">
               <%= link_to "投稿一覧", posts_path, class: "nav-link" %>
             </li>
             <li class="nav-item">
               <%= link_to "投稿画面", new_post_path, class: "nav-link" %>
             </li>
         </ul>
          <form class="form-inline my-2 my-lg-0"> 
            <ul class="navbar-nav mr-auto">
              <li class="nav-item">
                <%= link_to "マイページ", current_user, class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav-link", data: { confirm: 'ログアウトしますか?', cancel: 'やめる', commit: 'ログアウトする'}, title: 'ログアウト確認' %>
              </li>
            </ul>

          </form>
       <% else %>
          <div class="collapse navbar-collapse" id="navbarColor01">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item active">
              <li class="nav-item">
                <%= link_to "Co-sal Boardとは?", about_path, class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to 'ゲストログイン', users_guest_sign_in_path, method: :post, class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "ログイン", new_user_session_path, class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "新規登録", new_user_registration_path, class: "nav-link" %>
              </li>
            </ul>
          </div>
       <% end %>
   </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Co-sal Board</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.9.0/css/all.min.css" integrity="sha256-UzFD2WYH2U1dQpKDjjZK72VtPeWP50NoJjd26rnAdUI=" crossorigin="anonymous" />
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %> 
  </head>

  <body>
    <div id="main_wrapper">
      <header><%= render partial: "layouts/header" %></header>
      <%= render partial: "layouts/flash" %>
        <%= yield %>
      <%= render 'layouts/footer' %>

      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    </div>
  </body>  
</html>